---
- name: Install VSCode extensions
  become: false
  ansible.builtin.command: code --install-extension {{ item }}
  loop:
    - golang.go
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-python.vscode-pylance
    - redhat.vscode-yaml